### ISSUE TITLE
Tracker fails to play consecutive notes unless there is an explicit note-off between them

### ISSUE THREAD

**Issue by nathansnider** [gibbonjoyeux/VCV-Biset#5]
Any pattern without note-offs between the notes (including the pattern that the module is initialized with) will only play the first note. The second note in the pattern will close the gate for the first note, but will not open a gate for the new note or change the v/oct output. The third note and beyond have no effect at all. Notes are reset when a pattern loops, which appears to automatically insert a note off. 

I would think that when the tracker encounters a new note while a note is already playing, the ideal behavior would be to retrigger the gate and immediately change the v/oct output to the new note value (unless there is a glide, in which case the gate would remain open and smoothly transition to the new pitch). Also, in my opinion, it would be better for notes to continue to playing across pattern boundaries, since not every musical phrase resets "on the one." Perhaps there could be an option in the module to switch this behavior.

I didn't see the note-off command (entered with the ` character) mentioned in the manual, though perhaps I just missed it.

I am using Rack Pro 2.4.1 and Biset 2.0.5 on windows 10.

**Comment by gibbonjoyeux** [comment]
Thanks a lot ! I fixed the issue and sent it to VCV with other major bugs, it should be updated soon in the library :)
You can change your synth polyphonic channel count to >1 while the fix is waiting. To do so, right click on your synth (in the synth list on the Tracker module), move the slider and click on update synth :)

Thanks for the information on note-off command missing in the manual, that is really important !
