### ISSUE TITLE
Regex ?(1,2,3,4) interpretation issue

### ISSUE THREAD

**Issue by firolightfog** [gibbonjoyeux/VCV-Biset#6]
I have `>?(1,2,3,4) ` but it selects only 1, 2, or 3. 

It seems like the last value of the sequence is ignored.

**Comment by gibbonjoyeux** [comment]
Hello ! Thank you for this report :)

I tried to reproduce the bug both in clock mode and pitch mode but I can't get the same result unless the bias knob (bottom of the module) is <0%.
Is your 'bias' knob on 0% ? Otherwise it might change the random sequences behaviour, making it tend to choose values on the left (start) or on the right (end) of the sequence.

Still, it should not, at least on really small bias values, skip values on the sequence boundaries, so that's definitely a bug I should fix ! Thanks :)

**Comment by firolightfog** [comment]
Hm... I can't recreate the same error this time. Strange.

**Comment by firolightfog** [comment]
I can't recreate.
